### ISSUE TITLE
Missing AWS region, when baking an image on CentOS Stream 8 (worked on CentOS Linux 8)

### ISSUE THREAD

**Issue by Torniojaws** [NitorCreations/nameless-deploy-tools#22]
I'm trying to bake a new Jenkins image for EC2, but it ends up failing due to the AWS region being missing. However, you can see the region among the parameters in the playbook (`aws_region=eu-west-1'`). Interestingly, a lot of other parameters are also falsy in the failure stack trace - it's like the parameters that are in `extra_vars` are not being passed to the next step?

The below is with `ndt` version 1.212, but the same thing happens with the latest 1.241 too, so I wonder if there is a known incompatibility with `ndt` and CentOS Stream 8 (ami: `ami-0e0669c0b39d3a79f`)? The same config did work previously, on CentOS Linux 8 (non-Stream, that is - ami: `ami-0bfa4fefe067b7946`). The ultimate goal is to have baking work on CentOS Stream 9, though.

The failure (I obfuscated some details, do ask if something important is missing).

Just to be clear, the below is with:

- OS: CentOS Stream 8
- ndt: 1.212
- baking: CentOS Stream 8 + Jenkins

The odd thing is - and the reason why I'm baking on the same OS as the target - is that when I ran the bake locally on MacOS 12.1, it was successful and deployed it correctly with: `ndt deploy-stack f-jenkins f-jenkins "" aws_f_jenkins_bake`. So the same command seems to work on MacOS, but not on CentOS Stream 8.

```
PLAYBOOK: bake-image.yml *******************************************************
Positional arguments: /usr/local/lib/python3.9/site-packages/n_utils/includes/bake-image.yml
verbosity: 4
connection: smart
timeout: 10
flush_cache: True
become_method: sudo
tags: ('all',)
inventory: ('/etc/ansible/hosts',)
extra_vars: ('tools_version=1.212', 'ami_tag=bake_jenkins_0133', 'ami_id_file=/var/lib/jenkins/jenkins-home/jobs/bake-jenkins/workspace/ami-id.txt', 'job_name=bake_jenkins', 'aws_key_name=ci.f.com.rsa', 'app_user=f', 'app_home=/opt/f', 'build_number=0133', 'private_subnet=no', '{"packages": ["java-11-amazon-corretto-devel", "python3-pip", "wget", "rxvt-unicode", "lsof", "psmisc", "cryptsetup", "httpd", "mod_ssl", "git", "unzip", "zip", "libicu", "jenkins", "nodejs", "python3-devel", "libffi-devel", "openssl-devel", "gcc", "bzip2", "fail2ban", "fail2ban-systemd", "firewalld", "gcc-c++", "qt-devel", "xorg-x11-server-Xvfb", "squashfs-tools", "xmlstarlet", "sassc", "docker-ce-20.10.3-3.el8", "docker-ce-cli-20.10.3-3.el8", "make"]}', '{"files": ["viasatShare.py"]}', '{"bake_tags": {"environment": "nameless", "Name": "{{ job_name }} prototype"} }', 'prepare_script=/usr/local/lib/python3.9/site-packages/n_utils/includes/prepare.sh', '{"repos": []}', '{"keys": []}', 'base_ami_id=clean', 'bake_userdata=win-userdata.txt.j2', 'instance_type=t3.medium', 'timeout_min=55', 'root_ami=ami-0e0669c0b39d3a79f', 'tstamp=20220208101903', 'aws_region=eu-west-1', 'ansible_ssh_user=centos', 'imagedir=/var/lib/jenkins/jenkins-home/jobs/bake-jenkins/workspace/f-jenkins/image', 'subnet_id=subnet-xxx', 'sg_id=sg-xxx', 'amibake_instanceprofile=bakery-roles-resourceBakeInstanceprofile-xxx', 'pause_seconds=15', 'volume_size=10', '')
forks: 5
8 plays in /usr/local/lib/python3.9/site-packages/n_utils/includes/bake-image.yml

PLAY [Terminate any old instance(s)] *******************************************
META: ran handlers

TASK [amazon.aws.ec2_instance] *************************************************
task path: /usr/local/lib/python3.9/site-packages/n_utils/includes/bake-image.yml:22
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: jenkins
<127.0.0.1> EXEC /bin/sh -c 'echo ~jenkins && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/jenkins/jenkins-home/.ansible/tmp `"&& mkdir "` echo /var/lib/jenkins/jenkins-home/.ansible/tmp/ansible-tmp-1644308346.6186852-153785-223552843859711 `" && echo ansible-tmp-1644308346.6186852-153785-223552843859711="` echo /var/lib/jenkins/jenkins-home/.ansible/tmp/ansible-tmp-1644308346.6186852-153785-223552843859711 `" ) && sleep 0'
Using module file /usr/local/lib/python3.9/site-packages/ansible_collections/amazon/aws/plugins/modules/ec2_instance.py
<127.0.0.1> PUT /var/lib/jenkins/jenkins-home/.ansible/tmp/ansible-local-153781bsx_93rr/tmp3ey0eb7b TO /var/lib/jenkins/jenkins-home/.ansible/tmp/ansible-tmp-1644308346.6186852-153785-223552843859711/AnsiballZ_ec2_instance.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /var/lib/jenkins/jenkins-home/.ansible/tmp/ansible-tmp-1644308346.6186852-153785-223552843859711/ /var/lib/jenkins/jenkins-home/.ansible/tmp/ansible-tmp-1644308346.6186852-153785-223552843859711/AnsiballZ_ec2_instance.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3.9 /var/lib/jenkins/jenkins-home/.ansible/tmp/ansible-tmp-1644308346.6186852-153785-223552843859711/AnsiballZ_ec2_instance.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /var/lib/jenkins/jenkins-home/.ansible/tmp/ansible-tmp-1644308346.6186852-153785-223552843859711/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_amazon.aws.ec2_instance_payload_5ulydb6t/ansible_amazon.aws.ec2_instance_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/ec2.py", line 127, in boto3_conn
    return _boto3_conn(conn_type=conn_type, resource=resource, region=region, endpoint=endpoint, **params)
  File "/tmp/ansible_amazon.aws.ec2_instance_payload_5ulydb6t/ansible_amazon.aws.ec2_instance_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/ec2.py", line 163, in _boto3_conn
    return session.client(resource, config=config, region_name=region, endpoint_url=endpoint, **params)
  File "/usr/local/lib/python3.9/site-packages/boto3/session.py", line 270, in client
    return self._session.create_client(
  File "/usr/local/lib/python3.9/site-packages/botocore/session.py", line 870, in create_client
    client = client_creator.create_client(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 91, in create_client
    client_args = self._get_client_args(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 360, in _get_client_args
    return args_creator.get_client_args(
  File "/usr/local/lib/python3.9/site-packages/botocore/args.py", line 71, in get_client_args
    final_args = self.compute_client_args(
  File "/usr/local/lib/python3.9/site-packages/botocore/args.py", line 148, in compute_client_args
    endpoint_config = self._compute_endpoint_config(
  File "/usr/local/lib/python3.9/site-packages/botocore/args.py", line 234, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/args.py", line 320, in _resolve_endpoint
    return endpoint_bridge.resolve(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 441, in resolve
    resolved = self.endpoint_resolver.construct_endpoint(
  File "/usr/local/lib/python3.9/site-packages/botocore/regions.py", line 181, in construct_endpoint
    result = self._endpoint_for_partition(
  File "/usr/local/lib/python3.9/site-packages/botocore/regions.py", line 215, in _endpoint_for_partition
    raise NoRegionError()
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "availability_zone": null,
            "aws_access_key": null,
            "aws_ca_bundle": null,
            "aws_config": null,
            "aws_secret_key": null,
            "cpu_credit_specification": null,
            "cpu_options": null,
            "debug_botocore_endpoint_logs": false,
            "detailed_monitoring": null,
            "ebs_optimized": null,
            "ec2_url": null,
            "filters": {
                "image-id": "ami-0e0669c0b39d3a79f",
                "instance-type": "t3.medium",
                "instance.group-id": "sg-xxx",
                "subnet-id": "subnet-xxx",
                "tag:Name": "bake_jenkins prototype",
                "tag:environment": "nameless"
            },
            "image": null,
            "image_id": null,
            "instance_ids": [],
            "instance_initiated_shutdown_behavior": null,
            "instance_role": null,
            "instance_type": "t2.micro",
            "key_name": null,
            "launch_template": null,
            "metadata_options": null,
            "name": null,
            "network": null,
            "placement_group": null,
            "profile": null,
            "purge_tags": false,
            "region": null,
            "security_group": null,
            "security_groups": [],
            "security_token": null,
            "state": "terminated",
            "tags": null,
            "tenancy": null,
            "termination_protection": null,
            "tower_callback": null,
            "user_data": null,
            "validate_certs": true,
            "volumes": null,
            "vpc_subnet_id": null,
            "wait": true,
            "wait_timeout": 600
        }
    },
    "msg": "The amazon.aws.ec2_instance module requires a region and none was found in configuration, environment variables or module parameters"
}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

+ echo 'AMI baking failed'
AMI baking failed
+ exit 1
+ cleanup
+ '[' centos '!=' windows ']'
++ ssh-agent -k
+ eval unset 'SSH_AUTH_SOCK;' unset 'SSH_AGENT_PID;' echo Agent pid 153760 'killed;'
++ unset SSH_AUTH_SOCK
++ unset SSH_AGENT_PID
++ echo Agent pid 153760 killed
Agent pid 153760 killed
Build step 'Execute shell' marked build as failure
Archiving artifacts
Finished: FAILURE

```

**Comment by psiniemi** [comment]
Fixed in 1.242

**Comment by Torniojaws** [comment]
Hmm, the same issue still persist with the new 1.242. All details the same as above, and here's the vars and error:

```
extra_vars: ('tools_version=1.242', 'ami_tag=bake_jenkins_0134', 'ami_id_file=/var/lib/jenkins/jenkins-home/jobs/bake-jenkins/workspace/ami-id.txt', 'job_name=bake_jenkins', 'aws_key_name=ci.f.com.rsa', 'app_user=f', 'app_home=/opt/f', 'build_number=0134', 'private_subnet=no', '{"packages": ["java-11-amazon-corretto-devel", "python3-pip", "wget", "rxvt-unicode", "lsof", "psmisc", "cryptsetup", "httpd", "mod_ssl", "git", "unzip", "zip", "libicu", "jenkins", "nodejs", "python3-devel", "libffi-devel", "openssl-devel", "gcc", "bzip2", "fail2ban", "fail2ban-systemd", "firewalld", "gcc-c++", "qt-devel", "xorg-x11-server-Xvfb", "squashfs-tools", "xmlstarlet", "sassc", "docker-ce-20.10.3-3.el8", "docker-ce-cli-20.10.3-3.el8", "make"]}', '{"files": ["viasatShare.py"]}', '{"bake_tags": {"environment": "nameless", "Name": "{{ job_name }} prototype"} }', 'prepare_script=/usr/local/lib/python3.9/site-packages/n_utils/includes/prepare.sh', '{"repos": []}', '{"keys": []}', 'base_ami_id=clean', 'bake_userdata=win-userdata.txt.j2', 'instance_type=t3.medium', 'timeout_min=55', 'root_ami=ami-0e0669c0b39d3a79f', 'tstamp=20220208115143', 'aws_region=eu-west-1', 'ansible_ssh_user=centos', 'imagedir=/var/lib/jenkins/jenkins-home/jobs/bake-jenkins/workspace/f-jenkins/image', 'subnet_id=subnet-xxx', 'sg_id=sg-xxx', 'amibake_instanceprofile=bakery-roles-resourceBakeInstanceprofile-xxx', 'pause_seconds=15', 'volume_size=10', '')
```

```
PLAY [Terminate any old instance(s)] *******************************************
META: ran handlers

TASK [amazon.aws.ec2_instance] *************************************************
task path: /usr/local/lib/python3.9/site-packages/n_utils/includes/bake-image.yml:22
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: jenkins
<127.0.0.1> EXEC /bin/sh -c 'echo ~jenkins && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/jenkins/jenkins-home/.ansible/tmp `"&& mkdir "` echo /var/lib/jenkins/jenkins-home/.ansible/tmp/ansible-tmp-1644313906.504382-169598-37667831645699 `" && echo ansible-tmp-1644313906.504382-169598-37667831645699="` echo /var/lib/jenkins/jenkins-home/.ansible/tmp/ansible-tmp-1644313906.504382-169598-37667831645699 `" ) && sleep 0'
Using module file /usr/local/lib/python3.9/site-packages/ansible_collections/amazon/aws/plugins/modules/ec2_instance.py
<127.0.0.1> PUT /var/lib/jenkins/jenkins-home/.ansible/tmp/ansible-local-169594u1mhxwbu/tmp9gw_8s0i TO /var/lib/jenkins/jenkins-home/.ansible/tmp/ansible-tmp-1644313906.504382-169598-37667831645699/AnsiballZ_ec2_instance.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /var/lib/jenkins/jenkins-home/.ansible/tmp/ansible-tmp-1644313906.504382-169598-37667831645699/ /var/lib/jenkins/jenkins-home/.ansible/tmp/ansible-tmp-1644313906.504382-169598-37667831645699/AnsiballZ_ec2_instance.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3.9 /var/lib/jenkins/jenkins-home/.ansible/tmp/ansible-tmp-1644313906.504382-169598-37667831645699/AnsiballZ_ec2_instance.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /var/lib/jenkins/jenkins-home/.ansible/tmp/ansible-tmp-1644313906.504382-169598-37667831645699/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_amazon.aws.ec2_instance_payload_lzb1hisx/ansible_amazon.aws.ec2_instance_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/ec2.py", line 127, in boto3_conn
    return _boto3_conn(conn_type=conn_type, resource=resource, region=region, endpoint=endpoint, **params)
  File "/tmp/ansible_amazon.aws.ec2_instance_payload_lzb1hisx/ansible_amazon.aws.ec2_instance_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/ec2.py", line 163, in _boto3_conn
    return session.client(resource, config=config, region_name=region, endpoint_url=endpoint, **params)
  File "/usr/local/lib/python3.9/site-packages/boto3/session.py", line 270, in client
    return self._session.create_client(
  File "/usr/local/lib/python3.9/site-packages/botocore/session.py", line 870, in create_client
    client = client_creator.create_client(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 91, in create_client
    client_args = self._get_client_args(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 360, in _get_client_args
    return args_creator.get_client_args(
  File "/usr/local/lib/python3.9/site-packages/botocore/args.py", line 71, in get_client_args
    final_args = self.compute_client_args(
  File "/usr/local/lib/python3.9/site-packages/botocore/args.py", line 148, in compute_client_args
    endpoint_config = self._compute_endpoint_config(
  File "/usr/local/lib/python3.9/site-packages/botocore/args.py", line 234, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/args.py", line 320, in _resolve_endpoint
    return endpoint_bridge.resolve(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 441, in resolve
    resolved = self.endpoint_resolver.construct_endpoint(
  File "/usr/local/lib/python3.9/site-packages/botocore/regions.py", line 181, in construct_endpoint
    result = self._endpoint_for_partition(
  File "/usr/local/lib/python3.9/site-packages/botocore/regions.py", line 215, in _endpoint_for_partition
    raise NoRegionError()
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "availability_zone": null,
            "aws_access_key": null,
            "aws_ca_bundle": null,
            "aws_config": null,
            "aws_secret_key": null,
            "cpu_credit_specification": null,
            "cpu_options": null,
            "debug_botocore_endpoint_logs": false,
            "detailed_monitoring": null,
            "ebs_optimized": null,
            "ec2_url": null,
            "filters": {
                "image-id": "ami-0e0669c0b39d3a79f",
                "instance-type": "t3.medium",
                "instance.group-id": "sg-xxx",
                "subnet-id": "subnet-xxx",
                "tag:Name": "bake_jenkins prototype",
                "tag:environment": "nameless"
            },
            "image": null,
            "image_id": null,
            "instance_ids": [],
            "instance_initiated_shutdown_behavior": null,
            "instance_role": null,
            "instance_type": "t2.micro",
            "key_name": null,
            "launch_template": null,
            "metadata_options": null,
            "name": null,
            "network": null,
            "placement_group": null,
            "profile": null,
            "purge_tags": false,
            "region": null,
            "security_group": null,
            "security_groups": [],
            "security_token": null,
            "state": "terminated",
            "tags": null,
            "tenancy": null,
            "termination_protection": null,
            "tower_callback": null,
            "user_data": null,
            "validate_certs": true,
            "volumes": null,
            "vpc_subnet_id": null,
            "wait": true,
            "wait_timeout": 600
        }
    },
    "msg": "The amazon.aws.ec2_instance module requires a region and none was found in configuration, environment variables or module parameters"
}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

+ echo 'AMI baking failed'
AMI baking failed
+ exit 1
+ cleanup
+ '[' centos '!=' windows ']'
++ ssh-agent -k
+ eval unset 'SSH_AUTH_SOCK;' unset 'SSH_AGENT_PID;' echo Agent pid 169573 'killed;'
++ unset SSH_AUTH_SOCK
++ unset SSH_AGENT_PID
++ echo Agent pid 169573 killed
Agent pid 169573 killed
Build step 'Execute shell' marked build as failure
Archiving artifacts
Finished: FAILURE
```

**Comment by psiniemi** [comment]
Have you actually updated the ndt package on the baking instance and not just configured it to use 1.242?

**Comment by Torniojaws** [comment]
Yes, it was an older version (1.240). However, even after updating it on the server to 1.242, it still gives the same error when baking.

```
[centos@ci ~]$ ndt --version
1.242
[centos@ci ~]$ cat /etc/centos-release
CentOS Stream release 8
```
